services:
  - type: web
    name: youtube-direct-extractor
    region: ohio  # Options: ohio, oregon, frankfurt, singapore
    env: python
    buildCommand: |
        pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.6
    plan: free
    autoDeploy: true
    healthCheckPath: /health
